### ISSUE TITLE
Gitpod not letting Preview button work it's job

### ISSUE THREAD

**Issue by hazho** [wagtail/wagtail-gitpod#12]
gitpod has an issue not previewing the changes (error message is in browser console) 
image.png 
![image](https://user-images.githubusercontent.com/20362375/164409465-c01f3efd-3e0e-47f0-8e91-be9c2819e586.png)
as the rerror message says: gitpod is blocking the popups, which mean that the issue could be solved by gitpod repo (if someone knows where it is)

**Comment by allcaps** [comment]
The error explains what is happening:
> page-editor.js?v=73678ca7:1 Blocked opening '' in a new window because the request was made in a sandboxed frame whose 'allow-popups' permission is not set.

The Simple Browser (preview window) in Gitpod does not have the 'allow-popups' set. If you open the URL in a new tab, the preview opens fine.

There is nothing wrong with Wagtail or Wagtail Gitpod. This preview frame is part of Gitpod.

This can only be fixed upstream.

**Comment by hazho** [comment]
True true, I forgot to close this earlier
