### ISSUE TITLE
pyenv: version `3.8.2' is not installed (set by /workspace/wagtail-gitpod/.python-version)

### ISSUE THREAD

**Issue by IdanBanani** [wagtail/wagtail-gitpod#4]
gitpod /workspace/wagtail-gitpod $  HISTFILE=/workspace/.gitpod/cmd-0 history -r; {
> python -m pip install wagtail && wagtail start mysite . && python -m pip install -r requirements.txt && python manage.py migrate && echo "from django.contrib.auth import get_user_model; get_user_model().objects.create_superuser('admin', '', 'changeme')" | python3 manage.py shell
> 
> } && {
> python manage.py runserver 0.0.0.0:8080
> 
> }
pyenv: version `3.8.2' is not installed (set by /workspace/wagtail-gitpod/.python-version)

**Comment by allcaps** [comment]
@IdanBanani Thank you for reporting this. The Python version is now pinned at 3.8.3.
https://github.com/wagtail/wagtail-gitpod/pull/5
